export const forexPairs = {
  all: [
    "AUD/CAD",
    "AUD/CHF",
    "AUD/HKD",
    "AUD/JPY",
    "AUD/NZD",
    "AUD/SGD",
    "AUD/USD",
    "CAD/CHF",
    "CAD/HKD",
    "CAD/JPY",
    "CAD/SGD",
    "CHF/HKD",
    "CHF/JPY",
    "EUR/AUD",
    "EUR/CAD",
    "EUR/CHF",
    "EUR/CZK",
    "EUR/DKK",
    "EUR/GBP",
    "EUR/HKD",
    "EUR/HUF",
    "EUR/JPY",
    "EUR/NOK",
    "EUR/NZD",
    "EUR/PLN",
    "EUR/SEK",
    "EUR/SGD",
    "EUR/USD",
    "GBP/AUD",
    "GBP/CAD",
    "GBP/CHF",
    "GBP/HKD",
    "GBP/JPY",
    "GBP/NZD",
    "GBP/PLN",
    "GBP/SGD",
    "GBP/USD",
    "HKD/JPY",
    "NZD/CAD",
    "NZD/CHF",
    "NZD/HKD",
    "NZD/JPY",
    "NZD/SGD",
    "NZD/USD",
    "SGD/CHF",
    "SGD/HKD",
    "SGD/JPY",
    "USD/CAD",
    "USD/CHF",
    "USD/CNH",
    "USD/CZK",
    "USD/DKK",
    "USD/HKD",
    "USD/HUF",
    "USD/INR",
    "USD/JPY",
    "USD/MXN",
    "USD/NOK",
    "USD/PLN",
    "USD/SAR",
    "USD/SEK",
    "USD/SGD",
    "USD/THB",
    // "Copper",
    // "Natural Gas",
    // "Soybeans",
    // "Sugar",
    // "Crude Oil",
    // "Wheat",
    "Gold",
    "Palladium",
    "Platinum",
    "Silver",
    // "Australia 200",
    // "China A50",
    // "Europe 50",
    // "France 40",
    // "Germany 30",
    // "Hong Kong 33",
    // "India 50",
    // "Japan 225",
    // "Netherlands 25",
    // "Singapore 30",
    // "Taiwan Index",
    // "UK 100",
    // "US Nas 100",
    // "US Russ 2000",
    // "US SPX 500",
    // "US Wall St 30",
    // "Apple Inc",
    // "Microsoft Corporation",
    // "Amazon.com Inc",
    // "Tesla Inc",
    // "Alphabet Inc Class A (GOOGL)",
    // "Facebook Inc",
    // "Netflix Inc",
    // "EBay",
    // "Zoom Video Communications Inc (ZM)",
    // "BMW (Bayerische Motoren Werke AG)",
    // "Boeing Co (BA)",
    // "Moderna Inc (MRNA)",
    // "Pfizer Inc (PFE)",
    // "Adidas AG ADR (ADDYY)",
    // "Nikola Corp (NKLA)",
    // "Stewart Information Services Corp (STC)",
    // "Visa Inc Class A (V)",
    "BitCoin",
    "Ethereum",
    "Litecoin",
    "Ripple",
    "Aventus",
    "IOTA",
    "Ethereum Classic",
    "EOS",
    "OmiseGO",
    "Bitcoin Cash",
    "Bitcoin Gold",
    "Monero",
    "QTUM",
    "Zcash",
    "NEO",
    "DASH",
  ],
  popular: [
    "AUD/CAD",
    "AUD/USD",
    "EUR/GBP",
    "EUR/USD",
    "GBP/JPY",
    "GBP/USD",
    "USD/CAD",
    "USD/JPY",
    // "US SPX 500",
    // "US Wall St 30",
    // "Natural Gas",
    // "Crude Oil",
    // "Gold"
  ],
  favorites: [

  ],
  currencies: [
    "AUD/CAD",
    "AUD/CHF",
    "AUD/HKD",
    "AUD/JPY",
    "AUD/NZD",
    "AUD/SGD",
    "AUD/USD",
    "CAD/CHF",
    "CAD/HKD",
    "CAD/JPY",
    "CAD/SGD",
    "CHF/HKD",
    "CHF/JPY",
    "EUR/AUD",
    "EUR/CAD",
    "EUR/CHF",
    "EUR/CZK",
    "EUR/DKK",
    "EUR/GBP",
    "EUR/HKD",
    "EUR/HUF",
    "EUR/JPY",
    "EUR/NOK",
    "EUR/NZD",
    "EUR/PLN",
    "EUR/SEK",
    "EUR/SGD",
    "EUR/USD",
    "GBP/AUD",
    "GBP/CAD",
    "GBP/CHF",
    "GBP/HKD",
    "GBP/JPY",
    "GBP/NZD",
    "GBP/PLN",
    "GBP/SGD",
    "GBP/USD",
    "HKD/JPY",
    "NZD/CAD",
    "NZD/CHF",
    "NZD/HKD",
    "NZD/JPY",
    "NZD/SGD",
    "NZD/USD",
    "SGD/CHF",
    "SGD/HKD",
    "SGD/JPY",
    "USD/CAD",
    "USD/CHF",
    "USD/CNH",
    "USD/CZK",
    "USD/DKK",
    "USD/HKD",
    "USD/HUF",
    "USD/INR",
    "USD/JPY",
    "USD/MXN",
    "USD/NOK",
    "USD/PLN",
    "USD/SAR",
    "USD/SEK",
    "USD/SGD",
    "USD/THB",
  ],
  commodities: [
    // "Copper",
    // "Natural Gas",
    // "Soybeans",
    // "Sugar",
    // "Crude Oil",
    // "Wheat",
    "Gold",
    "Palladium",
    "Platinum",
    "Silver"
  ],
  indices: [
    // "Australia 200",
    // "China A50",
    // "Europe 50",
    // "France 40",
    // "Germany 30",
    // "Hong Kong 33",
    // "India 50",
    // "Japan 225",
    // "Netherlands 25",
    // "Singapore 30",
    // "Taiwan Index",
    // "UK 100",
    // "US Nas 100",
    // "US Russ 2000",
    // "US SPX 500",
    // "US Wall St 30"
  ],
  stocks: [
    // "Apple Inc",
    // "Microsoft Corporation",
    // "Amazon.com Inc",
    // "Tesla Inc",
    // "Alphabet Inc Class A (GOOGL)",
    // "Facebook Inc",
    // "Netflix Inc",
    // "EBay",
    // "Zoom Video Communications Inc (ZM)",
    // "BMW (Bayerische Motoren Werke AG)",
    // "Boeing Co (BA)",
    // "Moderna Inc (MRNA)",
    // "Pfizer Inc (PFE)",
    // "Adidas AG ADR (ADDYY)",
    // "Nikola Corp (NKLA)",
    // "Stewart Information Services Corp (STC)",
    // "Visa Inc Class A (V)"
  ],
  crypto: [
    "BitCoin",
    "Ethereum",
    "Litecoin",
    "Ripple",
    "Aventus",
    "IOTA",
    "Ethereum Classic",
    "EOS",
    "OmiseGO",
    "Bitcoin Cash",
    "Bitcoin Gold",
    "Monero",
    "QTUM",
    "Zcash",
    "NEO",
    "DASH"
  ]
}

export const assetMapping = {
  "AUD/CAD": "C:AUDCAD",
  "AUD/CHF": "C:AUDCHF",
  "AUD/HKD": "C:AUDHKD",
  "AUD/JPY": "C:AUDJPY",
  "AUD/NZD": "C:AUDNZD",
  "AUD/SGD": "C:AUDSGD",
  "AUD/USD": "C:AUDUSD",
  "CAD/CHF": "C:CADCHF",
  "CAD/HKD": "C:CADHKD",
  "CAD/JPY": "C:CADJPY",
  "CAD/SGD": "C:CADSGD",
  "CHF/HKD": "C:CHFHKD",
  "CHF/JPY": "C:CHFJPY",
  "EUR/AUD": "C:EURAUD",
  "EUR/CAD": "C:EURCAD",
  "EUR/CHF": "C:EURCHF",
  "EUR/CZK": "C:EURCZK",
  "EUR/DKK": "C:EURDKK",
  "EUR/GBP": "C:EURGBP",
  "EUR/HKD": "C:EURHKD",
  "EUR/HUF": "C:EURHUF",
  "EUR/JPY": "C:EURJPY",
  "EUR/NOK": "C:EURNOK",
  "EUR/NZD": "C:EURNZD",
  "EUR/PLN": "C:EURPLN",
  "EUR/SEK": "C:EURSEK",
  "EUR/SGD": "C:EURSGD",
  "EUR/USD": "C:EURUSD",
  "GBP/AUD": "C:GBPAUD",
  "GBP/CAD": "C:GBPCAD",
  "GBP/CHF": "C:GBPCHF",
  "GBP/HKD": "C:GBPHKD",
  "GBP/JPY": "C:GBPJPY",
  "GBP/NZD": "C:GBPNZD",
  "GBP/PLN": "C:GBPPLN",
  "GBP/SGD": "C:GBPSGD",
  "GBP/USD": "C:GBPUSD",
  "HKD/JPY": "C:HKDJPY",
  "NZD/CAD": "C:NZDCAD",
  "NZD/CHF": "C:NZDCHF",
  "NZD/HKD": "C:NZDHKD",
  "NZD/JPY": "C:NZDJPY",
  "NZD/SGD": "C:NZDSGD",
  "NZD/USD": "C:NZDUSD",
  "SGD/CHF": "C:SGDCHF",
  "SGD/HKD": "C:SGDHKD",
  "SGD/JPY": "C:SGDJPY",
  "USD/CAD": "C:USDCAD",
  "USD/CHF": "C:USDCHF",
  "USD/CNH": "C:USDCNH",
  "USD/CZK": "C:USDCZK",
  "USD/DKK": "C:USDDKK",
  "USD/HKD": "C:USDHKD",
  "USD/HUF": "C:USDHUF",
  "USD/INR": "C:USDINR",
  "USD/JPY": "C:USDJPY",
  "USD/MXN": "C:USDMXN",
  "USD/NOK": "C:USDNOK",
  "USD/PLN": "C:USDPLN",
  "USD/SAR": "C:USDSAR",
  "USD/SEK": "C:USDSEK",
  "USD/SGD": "C:USDSGD",
  "USD/THB": "C:USDTHB",

  // "Copper"      : "C:XCUUSD",
  // "Natural Gas" : "C:NATGASUSD",
  // "Soybeans"    : "C:SOYBNUSD",
  // "Sugar"       : "C:SUGARUSD",
  // "Crude Oil"   : "C:WTICOUSD",
  // "Wheat"       : "C:WHEATUSD",
  "Gold"        : "C:XAUUSD",
  "Palladium"   : "C:XPDUSD",
  "Platinum"    : "C:XPTUSD",
  "Silver"      : "C:XAGUSD",

  "Australia 200": "ASX:AXJO",
  "China A50": "C:CHINA50",
  "Europe 50": "EUROPE50",
  "France 40": "FRA40",
  "Germany 30": "GER30",
  "Hong Kong 33": "HK33",
  "India 50": "INDIA50",
  "Japan 225": "JP225",
  "Netherlands 25": "NL25",
  "Singapore 30": "SG30",
  "Taiwan Index": "TAIWANINDEX",
  "UK 100": "UK100",
  "US Nas 100": "USNAS100",
  "US Russ 2000": "US2000",
  "US SPX 500": "SPX500",
  "US Wall St 30": "US30",
  "Apple Inc": "AAPL",
  "Microsoft Corporation": "MSFT",
  "Amazon.com Inc": "AMZN",
  "Tesla Inc": "TSLA",
  "Alphabet Inc Class A (GOOGL)": "GOOGL",
  "Facebook Inc": "META",
  "Netflix Inc": "NFLX",
  "EBay": "EBAY",
  "Zoom Video Communications Inc (ZM)": "ZM",
  "BMW (Bayerische Motoren Werke AG)": "BMW",
  "Boeing Co (BA)": "BA",
  "Moderna Inc (MRNA)": "MRNA",
  "Pfizer Inc (PFE)": "PFE",
  "Adidas AG ADR (ADDYY)": "ADDYY",
  "Nikola Corp (NKLA)": "NKLA",
  "Stewart Information Services Corp (STC)": "STC",
  "Visa Inc Class A (V)": "V",
  "BitCoin": "X:BTCUSD",
  "Ethereum": "X:ETHUSD",
  "Litecoin": "X:LTCUSD",
  "Ripple": "X:XRPUSD",
  "Aventus": "X:AVTUSD",
  "IOTA": "X:IOTUSD",
  "Ethereum Classic": "X:ETCUSD",
  "EOS": "X:EOSUSD",
  "OmiseGO": "X:OMGUSD",
  "Bitcoin Cash": "X:BCHUSD",
  "Bitcoin Gold": "X:BTGUSD",
  "Monero": "X:XMRUSD",
  "QTUM": "X:QTUMUSD",
  "Zcash": "X:ZECUSD",
  "NEO": "X:NEOUSD",
  "DASH": "X:DASHUSD"
};

export const mainSubMapping = {
  "AUD/CAD": "C.C:AUD-CAD",
  "AUD/CHF": "C.C:AUD-CHF",
  "AUD/HKD": "C.C:AUD-HKD",
  "AUD/JPY": "C.C:AUD-JPY",
  "AUD/NZD": "C.C:AUD-NZD",
  "AUD/SGD": "C.C:AUD-SGD",
  "AUD/USD": "C.C:AUD-USD",
  "CAD/CHF": "C.C:CAD-CHF",
  "CAD/HKD": "C.C:CAD-HKD",
  "CAD/JPY": "C.C:CAD-JPY",
  "CAD/SGD": "C.C:CAD-SGD",
  "CHF/HKD": "C.C:CHF-HKD",
  "CHF/JPY": "C.C:CHF-JPY",
  "EUR/AUD": "C.C:EUR-AUD",
  "EUR/CAD": "C.C:EUR-CAD",
  "EUR/CHF": "C.C:EUR-CHF",
  "EUR/CZK": "C.C:EUR-CZK",
  "EUR/DKK": "C.C:EUR-DKK",
  "EUR/GBP": "C.C:EUR-GBP",
  "EUR/HKD": "C.C:EUR-HKD",
  "EUR/HUF": "C.C:EUR-HUF",
  "EUR/JPY": "C.C:EUR-JPY",
  "EUR/NOK": "C.C:EUR-NOK",
  "EUR/NZD": "C.C:EUR-NZD",
  "EUR/PLN": "C.C:EUR-PLN",
  "EUR/SEK": "C.C:EUR-SEK",
  "EUR/SGD": "C.C:EUR-SGD",
  "EUR/USD": "C.C:EUR-USD",
  "GBP/AUD": "C.C:GBP-AUD",
  "GBP/CAD": "C.C:GBP-CAD",
  "GBP/CHF": "C.C:GBP-CHF",
  "GBP/HKD": "C.C:GBP-HKD",
  "GBP/JPY": "C.C:GBP-JPY",
  "GBP/NZD": "C.C:GBP-NZD",
  "GBP/PLN": "C.C:GBP-PLN",
  "GBP/SGD": "C.C:GBP-SGD",
  "GBP/USD": "C.C:GBP-USD",
  "HKD/JPY": "C.C:HKD-JPY",
  "NZD/CAD": "C.C:NZD-CAD",
  "NZD/CHF": "C.C:NZD-CHF",
  "NZD/HKD": "C.C:NZD-HKD",
  "NZD/JPY": "C.C:NZD-JPY",
  "NZD/SGD": "C.C:NZD-SGD",
  "NZD/USD": "C.C:NZD-USD",
  "SGD/CHF": "C.C:SGD-CHF",
  "SGD/HKD": "C.C:SGD-HKD",
  "SGD/JPY": "C.C:SGD-JPY",
  "USD/CAD": "C.C:USD-CAD",
  "USD/CHF": "C.C:USD-CHF",
  "USD/CNH": "C.C:USD-CNH",
  "USD/CZK": "C.C:USD-CZK",
  "USD/DKK": "C.C:USD-DKK",
  "USD/HKD": "C.C:USD-HKD",
  "USD/HUF": "C.C:USD-HUF",
  "USD/INR": "C.C:USD-INR",
  "USD/JPY": "C.C:USD-JPY",
  "USD/MXN": "C.C:USD-MXN",
  "USD/NOK": "C.C:USD-NOK",
  "USD/PLN": "C.C:USD-PLN",
  "USD/SAR": "C.C:USD-SAR",
  "USD/SEK": "C.C:USD-SEK",
  "USD/SGD": "C.C:USD-SGD",
  "USD/THB": "C.C:USD-THB",

  // Uncomment and update if needed
  // "Copper"      : "C.C:XCU-USD",
  // "Natural Gas" : "C.C:NATGAS-USD",
  // "Soybeans"    : "C.C:SOYBN-USD",
  // "Sugar"       : "C.C:SUGAR-USD",
  // "Crude Oil"   : "C.C:WTICO-USD",
  // "Wheat"       : "C.C:WHEAT-USD",
  "Gold"        : "C.C:XAU-USD",
  "Palladium"   : "C.C:XPD-USD",
  "Platinum"    : "C.C:XPT-USD",
  "Silver"      : "C.C:XAG-USD",

  "Australia 200": "ASX:AXJO",
  "China A50": "C:CHINA50",
  "Europe 50": "EUROPE50",
  "France 40": "FRA40",
  "Germany 30": "GER30",
  "Hong Kong 33": "HK33",
  "India 50": "INDIA50",
  "Japan 225": "JP225",
  "Netherlands 25": "NL25",
  "Singapore 30": "SG30",
  "Taiwan Index": "TAIWANINDEX",
  "UK 100": "UK100",
  "US Nas 100": "USNAS100",
  "US Russ 2000": "US2000",
  "US SPX 500": "SPX500",
  "US Wall St 30": "US30",
  "Apple Inc": "AAPL",
  "Microsoft Corporation": "MSFT",
  "Amazon.com Inc": "AMZN",
  "Tesla Inc": "TSLA",
  "Alphabet Inc Class A (GOOGL)": "GOOGL",
  "Facebook Inc": "META",
  "Netflix Inc": "NFLX",
  "EBay": "EBAY",
  "Zoom Video Communications Inc (ZM)": "ZM",
  "BMW (Bayerische Motoren Werke AG)": "BMW",
  "Boeing Co (BA)": "BA",
  "Moderna Inc (MRNA)": "MRNA",
  "Pfizer Inc (PFE)": "PFE",
  "Adidas AG ADR (ADDYY)": "ADDYY",
  "Nikola Corp (NKLA)": "NKLA",
  "Stewart Information Services Corp (STC)": "STC",
  "Visa Inc Class A (V)": "V",
  "BitCoin":            "XQ.X:BTC-USD",
  "Ethereum":           "XQ.X:ETH-USD",
  "Litecoin":           "XQ.X:LTC-USD",
  "Ripple":             "XQ.X:XRP-USD",
  "Aventus":            "XQ.X:AVT-USD",
  "IOTA":               "XQ.X:IOT-USD",
  "Ethereum Classic":   "XQ.X:ETC-USD",
  "EOS":                "XQ.X:EOS-USD",
  "OmiseGO":            "XQ.X:OMG-USD",
  "Bitcoin Cash":       "XQ.X:BCH-USD",
  "Bitcoin Gold":       "XQ.X:BTG-USD",
  "Monero":             "XQ.X:XMR-USD",
  "QTUM":               "XQ.X:QTUM-USD",
  "Zcash":              "XQ.X:ZEC-USD",
  "NEO":                "XQ.X:NEO-USD",
  "DASH":               "XQ.X:DASH-USD"
};

export const extraSubMapping = {
  "AUD/CAD": "CAS.C:AUD-CAD",
  "AUD/CHF": "CAS.C:AUD-CHF",
  "AUD/HKD": "CAS.C:AUD-HKD",
  "AUD/JPY": "CAS.C:AUD-JPY",
  "AUD/NZD": "CAS.C:AUD-NZD",
  "AUD/SGD": "CAS.C:AUD-SGD",
  "AUD/USD": "CAS.C:AUD-USD",
  "CAD/CHF": "CAS.C:CAD-CHF",
  "CAD/HKD": "CAS.C:CAD-HKD",
  "CAD/JPY": "CAS.C:CAD-JPY",
  "CAD/SGD": "CAS.C:CAD-SGD",
  "CHF/HKD": "CAS.C:CHF-HKD",
  "CHF/JPY": "CAS.C:CHF-JPY",
  "EUR/AUD": "CAS.C:EUR-AUD",
  "EUR/CAD": "CAS.C:EUR-CAD",
  "EUR/CHF": "CAS.C:EUR-CHF",
  "EUR/CZK": "CAS.C:EUR-CZK",
  "EUR/DKK": "CAS.C:EUR-DKK",
  "EUR/GBP": "CAS.C:EUR-GBP",
  "EUR/HKD": "CAS.C:EUR-HKD",
  "EUR/HUF": "CAS.C:EUR-HUF",
  "EUR/JPY": "CAS.C:EUR-JPY",
  "EUR/NOK": "CAS.C:EUR-NOK",
  "EUR/NZD": "CAS.C:EUR-NZD",
  "EUR/PLN": "CAS.C:EUR-PLN",
  "EUR/SEK": "CAS.C:EUR-SEK",
  "EUR/SGD": "CAS.C:EUR-SGD",
  "EUR/USD": "CAS.C:EUR-USD",
  "GBP/AUD": "CAS.C:GBP-AUD",
  "GBP/CAD": "CAS.C:GBP-CAD",
  "GBP/CHF": "CAS.C:GBP-CHF",
  "GBP/HKD": "CAS.C:GBP-HKD",
  "GBP/JPY": "CAS.C:GBP-JPY",
  "GBP/NZD": "CAS.C:GBP-NZD",
  "GBP/PLN": "CAS.C:GBP-PLN",
  "GBP/SGD": "CAS.C:GBP-SGD",
  "GBP/USD": "CAS.C:GBP-USD",
  "HKD/JPY": "CAS.C:HKD-JPY",
  "NZD/CAD": "CAS.C:NZD-CAD",
  "NZD/CHF": "CAS.C:NZD-CHF",
  "NZD/HKD": "CAS.C:NZD-HKD",
  "NZD/JPY": "CAS.C:NZD-JPY",
  "NZD/SGD": "CAS.C:NZD-SGD",
  "NZD/USD": "CAS.C:NZD-USD",
  "SGD/CHF": "CAS.C:SGD-CHF",
  "SGD/HKD": "CAS.C:SGD-HKD",
  "SGD/JPY": "CAS.C:SGD-JPY",
  "USD/CAD": "CAS.C:USD-CAD",
  "USD/CHF": "CAS.C:USD-CHF",
  "USD/CNH": "CAS.C:USD-CNH",
  "USD/CZK": "CAS.C:USD-CZK",
  "USD/DKK": "CAS.C:USD-DKK",
  "USD/HKD": "CAS.C:USD-HKD",
  "USD/HUF": "CAS.C:USD-HUF",
  "USD/INR": "CAS.C:USD-INR",
  "USD/JPY": "CAS.C:USD-JPY",
  "USD/MXN": "CAS.C:USD-MXN",
  "USD/NOK": "CAS.C:USD-NOK",
  "USD/PLN": "CAS.C:USD-PLN",
  "USD/SAR": "CAS.C:USD-SAR",
  "USD/SEK": "CAS.C:USD-SEK",
  "USD/SGD": "CAS.C:USD-SGD",
  "USD/THB": "CAS.C:USD-THB",

  // Uncomment and update if needed
  // "Copper"      : "C.C:XCU-USD",
  // "Natural Gas" : "C.C:NATGAS-USD",
  // "Soybeans"    : "C.C:SOYBN-USD",
  // "Sugar"       : "C.C:SUGAR-USD",
  // "Crude Oil"   : "C.C:WTICO-USD",
  // "Wheat"       : "C.C:WHEAT-USD",
  "Gold"        : "CAS.C:XAU-USD",
  "Palladium"   : "CAS.C:XPD-USD",
  "Platinum"    : "CAS.C:XPT-USD",
  "Silver"      : "CAS.C:XAG-USD",

  "Australia 200": "ASX:AXJO",
  "China A50": "C:CHINA50",
  "Europe 50": "EUROPE50",
  "France 40": "FRA40",
  "Germany 30": "GER30",
  "Hong Kong 33": "HK33",
  "India 50": "INDIA50",
  "Japan 225": "JP225",
  "Netherlands 25": "NL25",
  "Singapore 30": "SG30",
  "Taiwan Index": "TAIWANINDEX",
  "UK 100": "UK100",
  "US Nas 100": "USNAS100",
  "US Russ 2000": "US2000",
  "US SPX 500": "SPX500",
  "US Wall St 30": "US30",
  "Apple Inc": "AAPL",
  "Microsoft Corporation": "MSFT",
  "Amazon.com Inc": "AMZN",
  "Tesla Inc": "TSLA",
  "Alphabet Inc Class A (GOOGL)": "GOOGL",
  "Facebook Inc": "META",
  "Netflix Inc": "NFLX",
  "EBay": "EBAY",
  "Zoom Video Communications Inc (ZM)": "ZM",
  "BMW (Bayerische Motoren Werke AG)": "BMW",
  "Boeing Co (BA)": "BA",
  "Moderna Inc (MRNA)": "MRNA",
  "Pfizer Inc (PFE)": "PFE",
  "Adidas AG ADR (ADDYY)": "ADDYY",
  "Nikola Corp (NKLA)": "NKLA",
  "Stewart Information Services Corp (STC)": "STC",
  "Visa Inc Class A (V)": "V",
  "BitCoin":            "XAS.X:BTC-USD",
  "Ethereum":           "XAS.X:ETH-USD",
  "Litecoin":           "XAS.X:LTC-USD",
  "Ripple":             "XAS.X:XRP-USD",
  "Aventus":            "XAS.X:AVT-USD",
  "IOTA":               "XAS.X:IOT-USD",
  "Ethereum Classic":   "XAS.X:ETC-USD",
  "EOS":                "XAS.X:EOS-USD",
  "OmiseGO":            "XAS.X:OMG-USD",
  "Bitcoin Cash":       "XAS.X:BCH-USD",
  "Bitcoin Gold":       "XAS.X:BTG-USD",
  "Monero":             "XAS.X:XMR-USD",
  "QTUM":               "XAS.X:QTUM-USD",
  "Zcash":              "XAS.X:ZEC-USD",
  "NEO":                "XAS.X:NEO-USD",
  "DASH":               "XAS.X:DASH-USD"
};

export const nameToPairMapping = {
  "Gold"        : "XAU/USD",
  "Palladium"   : "XPD/USD",
  "Platinum"    : "XPT/USD",
  "Silver"      : "XAG/USD",
  "BitCoin":            "BTC-USD",
  "Ethereum":           "ETH-USD",
  "Litecoin":           "LTC-USD",
  "Ripple":             "XRP-USD",
  "Aventus":            "AVT-USD",
  "IOTA":               "IOT-USD",
  "Ethereum Classic":   "ETC-USD",
  "EOS":                "EOS-USD",
  "OmiseGO":            "OMG-USD",
  "Bitcoin Cash":       "BCH-USD",
  "Bitcoin Gold":       "BTG-USD",
  "Monero":             "XMR-USD",
  "QTUM":               "QTUM-USD",
  "Zcash":              "ZEC-USD",
  "NEO":                "NEO-USD",
  "DASH":               "DASH-USD"
}


export const tradingViewMapping = {
  "AUD/CAD": "OANDA:AUDCAD",
  "AUD/CHF": "OANDA:AUDCHF",
  "AUD/HKD": "OANDA:AUDHKD",
  "AUD/JPY": "OANDA:AUDJPY",
  "AUD/NZD": "OANDA:AUDNZD",
  "AUD/SGD": "OANDA:AUDSGD",
  "AUD/USD": "OANDA:AUDUSD",
  "CAD/CHF": "OANDA:CADCHF",
  "CAD/HKD": "OANDA:CAPHKD",
  "CAD/JPY": "OANDA:CADJPY",
  "CAD/SGD": "OANDA:CADSGD",
  "CHF/HKD": "OANDA:CHFHKD",
  "CHF/JPY": "OANDA:CHFJPY",
  "EUR/AUD": "OANDA:EURAUD",
  "EUR/CAD": "OANDA:EURCAD",
  "EUR/CHF": "OANDA:EURCHF",
  "EUR/CZK": "OANDA:EURCZK",
  "EUR/DKK": "OANDA:EURDKK",
  "EUR/GBP": "OANDA:EURGBP",
  "EUR/HKD": "OANDA:EURHKD",
  "EUR/HUF": "OANDA:EURHUF",
  "EUR/JPY": "OANDA:EURJPY",
  "EUR/NOK": "OANDA:EURNOK",
  "EUR/NZD": "OANDA:EURNZD",
  "EUR/PLN": "OANDA:EURPLN",
  "EUR/SEK": "OANDA:EURSEK",
  "EUR/SGD": "OANDA:EURSGD",
  "EUR/USD": "OANDA:EURUSD",
  "GBP/AUD": "OANDA:GBPAUD",
  "GBP/CAD": "OANDA:GBPCAD",
  "GBP/CHF": "OANDA:GBPCHF",
  "GBP/HKD": "OANDA:GBPHKD",
  "GBP/JPY": "OANDA:GBPJPY",
  "GBP/NZD": "OANDA:GBPNZD",
  "GBP/PLN": "OANDA:GBPPLN",
  "GBP/SGD": "OANDA:GBPSGD",
  "GBP/USD": "OANDA:GBPUSD",
  "HKD/JPY": "OANDA:HKDJPY",
  "NZD/CAD": "OANDA:NZDCAD",
  "NZD/CHF": "OANDA:NZDCHF",
  "NZD/HKD": "OANDA:NZDHKD",
  "NZD/JPY": "OANDA:NZDJPY",
  "NZD/SGD": "OANDA:NZDSGD",
  "NZD/USD": "OANDA:NZDUSD",
  "SGD/CHF": "OANDA:SGDCHF",
  "SGD/HKD": "OANDA:SGDHKD",
  "SGD/JPY": "OANDA:SGDJPY",
  "USD/CAD": "OANDA:USDCAD",
  "USD/CHF": "OANDA:USDCHF",
  "USD/CNH": "OANDA:USDCNH",
  "USD/CZK": "OANDA:USDCZK",
  "USD/DKK": "OANDA:USDDKK",
  "USD/HKD": "OANDA:USDHKD",
  "USD/HUF": "OANDA:USDHUF",
  "USD/INR": "USDINR",
  "USD/JPY": "OANDA:USDJPY",
  "USD/MXN": "OANDA:USDMXN",
  "USD/NOK": "OANDA:USDNOK",
  "USD/PLN": "OANDA:USDPLN",
  "USD/SAR": "USDSAR",
  "USD/SEK": "OANDA:USDSEK",
  "USD/SGD": "OANDA:USDSGD",
  "USD/THB": "OANDA:USDTHB",
  // "Copper"      : "OANDA:XCUUSD",
  // "Natural Gas" : "OANDA:NATGASUSD",
  // "Soybeans"    : "OANDA:SOYBNUSD",
  // "Sugar"       : "OANDA:SUGARUSD",
  // "Crude Oil"   : "OANDA:WTICOUSD",
  // "Wheat"       : "OANDA:WHEATUSD",
  "Gold"        : "OANDA:XAUUSD",
  "Palladium"   : "OANDA:XPDUSD",
  "Platinum"    : "OANDA:XPTUSD",
  "Silver"      : "OANDA:XAGUSD",
  "Australia 200": "ASX:XJO",
  "China A50": "X:FTX",
  "Europe 50": "X:STOXX50E",
  "France 40": "Euronext:PX1",
  "Germany 30": "EUREX:FDAX",
  "Hong Kong 33": "X:HSI",
  "India 50": "NSE:NIFTY",
  "Japan 225": "X:NK225",
  "Netherlands 25": "Euronext:AMS25",
  "Singapore 30": "SGX:STI",
  "Taiwan Index": "X:TWSE",
  "UK 100": "X:LXUK",
  "US Nas 100": "X:NDX",
  "US Russ 2000": "X:RUT",
  "US SPX 500": "X:SPX",
  "US Wall St 30": "X:DJIA",
  "Apple Inc": "X:AAPL",
  "Microsoft Corporation": "X:MSFT",
  "Amazon.com Inc": "X:AMZN",
  "Tesla Inc": "X:TSLA",
  "Alphabet Inc Class A (GOOGL)": "X:GOOGL",
  "Facebook Inc": "X:FB",
  "Netflix Inc": "NFLX",
  "EBay": "X:EBAY",
  "Zoom Video Communications Inc (ZM)": "X:ZM",
  "BMW (Bayerische Motoren Werke AG)": "X:BMW",
  "Boeing Co (BA)": "X:BA",
  "Moderna Inc (MRNA)": "X:MRNA",
  "Pfizer Inc (PFE)": "X:PFE",
  "Adidas AG ADR (ADDYY)": "X:ADDYY",
  "Nikola Corp (NKLA)": "X:NKLA",
  "Stewart Information Services Corp (STC)": "X:STC",
  "Visa Inc Class A (V)": "X:V",
  "BitCoin": "CRYPTO:BTCUSD",
  "Ethereum": "CRYPTO:ETHUSD",
  "Litecoin": "CRYPTO:LTCUSD",
  "Ripple": "CRYPTO:XRPUSD",
  "Aventus": "AVTUSD",
  "IOTA": "IOTUSD",
  "Ethereum Classic": "CRYPTO:ETCUSD",
  "EOS": "CRYPTO:EOSUSD",
  "OmiseGO": "CRYPTO:OMGUSD",
  "Bitcoin Cash": "CRYPTO:BCHUSD",
  "Bitcoin Gold": "CRYPTO:BTGUSD",
  "Monero": "CRYPTO:XMRUSD",
  "QTUM":   "CRYPTO:QTUMUSD",
  "Zcash":  "CRYPTO:ZECUSD",
  "NEO":    "CRYPTO:NEOUSD",
  "DASH":   "CRYPTO:DASHUSD",
};

export const typeMapping = {
  // Currencies
  "AUD/CAD": "currencies",
  "AUD/CHF": "currencies",
  "AUD/HKD": "currencies",
  "AUD/JPY": "currencies",
  "AUD/NZD": "currencies",
  "AUD/SGD": "currencies",
  "AUD/USD": "currencies",
  "CAD/CHF": "currencies",
  "CAD/HKD": "currencies",
  "CAD/JPY": "currencies",
  "CAD/SGD": "currencies",
  "CHF/HKD": "currencies",
  "CHF/JPY": "currencies",
  "EUR/AUD": "currencies",
  "EUR/CAD": "currencies",
  "EUR/CHF": "currencies",
  "EUR/CZK": "currencies",
  "EUR/DKK": "currencies",
  "EUR/GBP": "currencies",
  "EUR/HKD": "currencies",
  "EUR/HUF": "currencies",
  "EUR/JPY": "currencies",
  "EUR/NOK": "currencies",
  "EUR/NZD": "currencies",
  "EUR/PLN": "currencies",
  "EUR/SEK": "currencies",
  "EUR/SGD": "currencies",
  "EUR/USD": "currencies",
  "GBP/AUD": "currencies",
  "GBP/CAD": "currencies",
  "GBP/CHF": "currencies",
  "GBP/HKD": "currencies",
  "GBP/JPY": "currencies",
  "GBP/NZD": "currencies",
  "GBP/PLN": "currencies",
  "GBP/SGD": "currencies",
  "GBP/USD": "currencies",
  "HKD/JPY": "currencies",
  "NZD/CAD": "currencies",
  "NZD/CHF": "currencies",
  "NZD/HKD": "currencies",
  "NZD/JPY": "currencies",
  "NZD/SGD": "currencies",
  "NZD/USD": "currencies",
  "SGD/CHF": "currencies",
  "SGD/HKD": "currencies",
  "SGD/JPY": "currencies",
  "USD/CAD": "currencies",
  "USD/CHF": "currencies",
  "USD/CNH": "currencies",
  "USD/CZK": "currencies",
  "USD/DKK": "currencies",
  "USD/HKD": "currencies",
  "USD/HUF": "currencies",
  "USD/INR": "currencies",
  "USD/JPY": "currencies",
  "USD/MXN": "currencies",
  "USD/NOK": "currencies",
  "USD/PLN": "currencies",
  "USD/SAR": "currencies",
  "USD/SEK": "currencies",
  "USD/SGD": "currencies",
  "USD/THB": "currencies",

  // Commodities
  "Copper": "commodities",
  "Gold": "commodities",
  "Palladium": "commodities",
  "Platinum": "commodities",
  "Silver": "commodities",
  "Natural Gas" : "commodities",
  "Soybeans"    : "commodities",
  "Sugar"       : "commodities",
  "Crude Oil"   : "commodities",
  "Wheat"       : "commodities",

  // Indices
  "Australia 200": "indices",
  "China A50": "indices",
  "Europe 50": "indices",
  "France 40": "indices",
  "Germany 30": "indices",
  "Hong Kong 33": "indices",
  "India 50": "indices",
  "Japan 225": "indices",
  "Netherlands 25": "indices",
  "Singapore 30": "indices",
  "Taiwan Index": "indices",
  "UK 100": "indices",
  "US Nas 100": "indices",
  "US Russ 2000": "indices",
  "US SPX 500": "indices",
  "US Wall St 30": "indices",

  // Stocks
  "Apple Inc": "stocks",
  "Microsoft Corporation": "stocks",
  "Amazon.com Inc": "stocks",
  "Tesla Inc": "stocks",
  "Alphabet Inc Class A (GOOGL)": "stocks",
  "Facebook Inc": "stocks",
  "Netflix Inc": "stocks",
  "EBay": "stocks",
  "Zoom Video Communications Inc (ZM)": "stocks",
  "BMW (Bayerische Motoren Werke AG)": "stocks",
  "Boeing Co (BA)": "stocks",
  "Moderna Inc (MRNA)": "stocks",
  "Pfizer Inc (PFE)": "stocks",
  "Adidas AG ADR (ADDYY)": "stocks",
  "Nikola Corp (NKLA)": "stocks",
  "Stewart Information Services Corp (STC)": "stocks",
  "Visa Inc Class A (V)": "stocks",

  // Crypto
  "BitCoin": "crypto",
  "Ethereum": "crypto",
  "Litecoin": "crypto",
  "Ripple": "crypto",
  "Aventus": "crypto",
  "IOTA": "crypto",
  "Ethereum Classic": "crypto",
  "EOS": "crypto",
  "OmiseGO": "crypto",
  "Bitcoin Cash": "crypto",
  "Bitcoin Gold": "crypto",
  "Monero": "crypto",
  "QTUM": "crypto",
  "Zcash": "crypto",
  "NEO": "crypto",
  "DASH": "crypto"
};
