const forexPairs = {
  all: [
    "AUD/CAD",
    "AUD/CHF",
    "AUD/HKD",
    "AUD/JPY",
    "AUD/NZD",
    "AUD/SGD",
    "AUD/USD",
    "CAD/CHF",
    "CAD/HKD",
    "CAD/JPY",
    "CAD/SGD",
    "CHF/HKD",
    "CHF/JPY",
    "EUR/AUD",
    "EUR/CAD",
    "EUR/CHF",
    "EUR/CZK",
    "EUR/DKK",
    "EUR/GBP",
    "EUR/HKD",
    "EUR/HUF",
    "EUR/JPY",
    "EUR/NOK",
    "EUR/NZD",
    "EUR/PLN",
    "EUR/SEK",
    "EUR/SGD",
    "EUR/USD",
    "GBP/AUD",
    "GBP/CAD",
    "GBP/CHF",
    "GBP/HKD",
    "GBP/JPY",
    "GBP/NZD",
    "GBP/PLN",
    "GBP/SGD",
    "GBP/USD",
    "HKD/JPY",
    "NZD/CAD",
    "NZD/CHF",
    "NZD/HKD",
    "NZD/JPY",
    "NZD/SGD",
    "NZD/USD",
    "SGD/CHF",
    "SGD/HKD",
    "SGD/JPY",
    "USD/CAD",
    "USD/CHF",
    "USD/CNH",
    "USD/CZK",
    "USD/DKK",
    "USD/HKD",
    "USD/HUF",
    "USD/INR",
    "USD/JPY",
    "USD/MXN",
    "USD/NOK",
    "USD/PLN",
    "USD/SAR",
    "USD/SEK",
    "USD/SGD",
    "USD/THB",
    "Copper",
    "Natural Gas",
    "Soybeans",
    "Sugar",
    "Crude Oil",
    "Wheat",
    "Gold",
    "Palladium",
    "Platinum",
    "Silver",
    "Australia 200",
    "China A50",
    "Europe 50",
    "France 40",
    "Germany 30",
    "Hong Kong 33",
    "India 50",
    "Japan 225",
    "Netherlands 25",
    "Singapore 30",
    "Taiwan Index",
    "UK 100",
    "US Nas 100",
    "US Russ 2000",
    "US SPX 500",
    "US Wall St 30",
    "Apple Inc",
    "Microsoft Corporation",
    "Amazon.com Inc",
    "Tesla Inc",
    "Alphabet Inc Class A (GOOGL)",
    "Facebook Inc",
    "Netflix Inc",
    "EBay",
    "Zoom Video Communications Inc (ZM)",
    "BMW (Bayerische Motoren Werke AG)",
    "Boeing Co (BA)",
    "Moderna Inc (MRNA)",
    "Pfizer Inc (PFE)",
    "Adidas AG ADR (ADDYY)",
    "Nikola Corp (NKLA)",
    "Stewart Information Services Corp (STC)",
    "Visa Inc Class A (V)",
    "BitCoin",
    "Ethereum",
    "Litecoin",
    "Ripple",
    "Aventus",
    "IOTA",
    "Ethereum Classic",
    "EOS",
    "OmiseGO",
    "Bitcoin Cash",
    "Bitcoin Gold",
    "Monero",
    "QTUM",
    "Zcash",
    "NEO",
    "DASH",
  ],
  popular: [
    "AUD/CAD",
    "AUD/USD",
    "EUR/GBP",
    "EUR/USD",
    "GBP/JPY",
    "GBP/USD",
    "USD/CAD",
    "USD/JPY",
    "US SPX 500",
    "US Wall St 30",
    "Natural Gas",
    "Crude Oil",
    "Gold"
  ],
  favorites: [

  ],
  currencies: [
    "AUD/CAD",
    "AUD/CHF",
    "AUD/HKD",
    "AUD/JPY",
    "AUD/NZD",
    "AUD/SGD",
    "AUD/USD",
    "CAD/CHF",
    "CAD/HKD",
    "CAD/JPY",
    "CAD/SGD",
    "CHF/HKD",
    "CHF/JPY",
    "EUR/AUD",
    "EUR/CAD",
    "EUR/CHF",
    "EUR/CZK",
    "EUR/DKK",
    "EUR/GBP",
    "EUR/HKD",
    "EUR/HUF",
    "EUR/JPY",
    "EUR/NOK",
    "EUR/NZD",
    "EUR/PLN",
    "EUR/SEK",
    "EUR/SGD",
    "EUR/USD",
    "GBP/AUD",
    "GBP/CAD",
    "GBP/CHF",
    "GBP/HKD",
    "GBP/JPY",
    "GBP/NZD",
    "GBP/PLN",
    "GBP/SGD",
    "GBP/USD",
    "HKD/JPY",
    "NZD/CAD",
    "NZD/CHF",
    "NZD/HKD",
    "NZD/JPY",
    "NZD/SGD",
    "NZD/USD",
    "SGD/CHF",
    "SGD/HKD",
    "SGD/JPY",
    "USD/CAD",
    "USD/CHF",
    "USD/CNH",
    "USD/CZK",
    "USD/DKK",
    "USD/HKD",
    "USD/HUF",
    "USD/INR",
    "USD/JPY",
    "USD/MXN",
    "USD/NOK",
    "USD/PLN",
    "USD/SAR",
    "USD/SEK",
    "USD/SGD",
    "USD/THB",
  ],
  commodities: [
    "Copper",
    "Natural Gas",
    "Soybeans",
    "Sugar",
    "Crude Oil",
    "Wheat",
    "Gold",
    "Palladium",
    "Platinum",
    "Silver"
  ],
  indices: [
    "Australia 200",
    "China A50",
    "Europe 50",
    "France 40",
    "Germany 30",
    "Hong Kong 33",
    "India 50",
    "Japan 225",
    "Netherlands 25",
    "Singapore 30",
    "Taiwan Index",
    "UK 100",
    "US Nas 100",
    "US Russ 2000",
    "US SPX 500",
    "US Wall St 30"
  ],
  stocks: [
    "Apple Inc",
    "Microsoft Corporation",
    "Amazon.com Inc",
    "Tesla Inc",
    "Alphabet Inc Class A (GOOGL)",
    "Facebook Inc",
    "Netflix Inc",
    "EBay",
    "Zoom Video Communications Inc (ZM)",
    "BMW (Bayerische Motoren Werke AG)",
    "Boeing Co (BA)",
    "Moderna Inc (MRNA)",
    "Pfizer Inc (PFE)",
    "Adidas AG ADR (ADDYY)",
    "Nikola Corp (NKLA)",
    "Stewart Information Services Corp (STC)",
    "Visa Inc Class A (V)"
  ],
  crypto: [
    "BitCoin",
    "Ethereum",
    "Litecoin",
    "Ripple",
    "Aventus",
    "IOTA",
    "Ethereum Classic",
    "EOS",
    "OmiseGO",
    "Bitcoin Cash",
    "Bitcoin Gold",
    "Monero",
    "QTUM",
    "Zcash",
    "NEO",
    "DASH"
  ]
}

export default forexPairs